volumes:
  db-data:

services:
  db:
    image: postgres:latest
    container_name: rent-control-db
    environment:
      POSTGRES_USER: rentalcontrol
      POSTGRES_PASSWORD: rentalcontrol
      POSTGRES_DB: RentalControl
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  postgrest:
    image: postgrest/postgrest
    container_name: rent-control-postgrest
    environment:
      PGRST_DB_URI: postgres://rentalcontrol:rentalcontrol@db/RentalControl
      PGRST_DB_ANON_ROLE: rentalcontrol
      PGRST_DB_SCHEMA: public
      PGRST_SERVER_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  rentalcontrol:
    image: rentalcontrol
    container_name: rental-control-app
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: RentalControl/Dockerfile
